# -*- coding: utf-8 -*-

import logging
import re
from statistics import mean
from typing import List, Dict, Any, Tuple, Optional

from sacrebleu.metrics.bleu import BLEU
from argparse import ArgumentParser

import unicodedata
import yaml
import json
import os

from qwen3_forcealign_tokenizer import Qwen3ForceAlignTokenizer
qwen_tok = Qwen3ForceAlignTokenizer()
def _qwen_units(text: str, language: str) -> List[str]:
    return qwen_tok.encode_timestamp(_norm(text), language)

'''
python main_new3.py `
  --yaml_file data/input/ACL.ACLdev2023.en-xx.gold_segments.yaml `
  --source_sentences_file data/input/ACL.6060.dev.en-xx.en.txt `
  --instances_log data/output_qwen_asr3/instances.log `
  --segale_file data/output_segale3/hyp/aligned_spacy_hyp.jsonl `
  --asr_dir data/output_qwen_asr3 `
  --output_folder data/output_longyaal3 `
  --bleu_tokenizer zh 

python main_new3.py
'''

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

INF = float("inf")


# ============================================================
# 原样保留：Instance / BLEU / YAAL
# ============================================================
class Instance:
    """
    Stores the information about the output instances generated by SimulEval.
    """

    def __init__(self, info: Dict[str, Any], latency_unit: str = "word"):
        for key, value in info.items():
            setattr(self, key, value)

        self.reference = info.get("reference", "")  # 文本
        self.prediction = info.get("prediction", "")  # 文本
        self.latency_unit = latency_unit
        self.metrics = {}

    @property
    def reference_length(self) -> int:  # ref 文本长度
        return self.string_to_len(self.reference, self.latency_unit)

    @staticmethod
    def string_to_len(string: str, latency_unit: str) -> int:
        if latency_unit == "word":
            return len(string.split(" "))
        elif latency_unit == "char":
            return len(string.strip())
        else:
            assert False, f"Unknown latency unit: {latency_unit}"

# --------------------------------------------------------------
class SacreBLEUScorer:
    def __init__(self, tokenizer: str = "13a") -> None:
        super().__init__()
        self.logger = logging.getLogger("simuleval.scorer.bleu")
        self.tokenizer = tokenizer

    def __call__(self, instances: Dict) -> float:
        try:
            return (
                BLEU(tokenize=self.tokenizer)
                .corpus_score(
                    [ins.prediction for ins in instances.values()],
                    [[ins.reference for ins in instances.values()]],
                )
                .score
            )
        except Exception as e:
            self.logger.error(str(e))
            return 0

# --------------------------------------------------------------
class YAALScorer:
    r"""
    YAAL: Yet Another Average Lagging
    你这里既支持：
    - computation_unaware：用 delays
    - computation_aware：用 elapsed
    同时支持 longform（允许超过 source_length，用 recording_end 截断）。
    """

    def __init__(self, computation_aware: bool = False, is_longform: bool = False, force_unit_target_len: bool = True):
        self.computation_aware = computation_aware
        self.is_longform = is_longform
        self.force_unit_target_len = force_unit_target_len  # NEW: 强制用 unit 数作为 target_length（不管 ref 文本长度），适合 s2s/unit 场景

    def get_delays_lengths(self, ins: Instance):
        timestamp_type = "delays" if not self.computation_aware else "elapsed"
        delays = getattr(ins, timestamp_type, None)
        assert delays

        src_len = ins.source_length

        # ✅ 关键：unit-level latency 时，tgt_len 就是 unit 数
        if self.force_unit_target_len:
            tgt_len = len(delays)
        else:
            tgt_len = ins.reference_length  # 旧逻辑（一般不适合 s2s/unit）

        return delays, src_len, tgt_len

    def compute(self, ins: Instance):
        delays, source_length, target_length = self.get_delays_lengths(ins)

        is_longform = hasattr(ins, "longform") or self.is_longform
        
        recording_end = (
            ins.recording_end if hasattr(ins, "recording_end") else float("inf")
        )

        if (delays[0] >= source_length and not is_longform) or (
            delays[0] >= recording_end
        ):
            return None

        LAAL = 0
        gamma = max(len(delays), target_length) / source_length
        tau = 0
        for t_minus_1, d in enumerate(delays):

            if (d >= source_length and not is_longform) or (d >= recording_end):
                break

            LAAL += d - t_minus_1 / gamma
            tau = t_minus_1 + 1

        LAAL /= tau
        return LAAL

    def __call__(self, instances: Dict[int, Instance]) -> float:
        scores = []
        timestamp_type = "elapsed" if self.computation_aware else "delays"
        for index, ins in instances.items():
            delays = getattr(ins, timestamp_type, None)
            if delays is None or len(delays) == 0:
                logger.warning(f"Instance {index} has no delay information. Skipped")
                continue
            score = self.compute(ins)
            if score is None:
                continue
            scores.append(score)

        return mean(scores) if len(scores) > 0 else float("nan")
# --------------------------------------------------------------

def evaluate_instances(
    resegmented_instances: List[Instance], tokenizer: str
) -> Dict[str, float]:
    ca_unaware_yaal_scorer = YAALScorer(is_longform=True, force_unit_target_len=True)
    ca_aware_yaal_scorer  = YAALScorer(computation_aware=True, is_longform=True, force_unit_target_len=True)
    bleu_scorer = SacreBLEUScorer(tokenizer)

    resegmented_instances_dict = {i: ins for i, ins in enumerate(resegmented_instances)}
    ca_unaware_yaal_score = ca_unaware_yaal_scorer(resegmented_instances_dict)
    ca_aware_yaal_score = ca_aware_yaal_scorer(resegmented_instances_dict)

    bleu_score = bleu_scorer(resegmented_instances_dict)

    return {
        "ca_unaware_yaal": ca_unaware_yaal_score,
        "ca_aware_yaal": ca_aware_yaal_score,
        "bleu": bleu_score,
    }


# ============================================================
# 关键新增：为了把 segale -> unit 下标 -> 切 delays
# ============================================================
def _to_ms(x: Any) -> float:
    """
    把长度/时间统一到毫秒：
    - x=None / 无法转 float / <=0 -> INF
    - 小于 1e4 的认为是“秒”，乘 1000
      （因为很多 instances.log 里 source_length 是秒，而 delays 常是 ms）
    - >=1e4 的认为已经是 ms
    ⚠️ 隐含假设：秒不会超过 1e4（也就是 10000 秒 ≈ 2.7 小时）。
    """
    if x is None:
        return INF
    try:
        v = float(x)
    except Exception:
        return INF
    if v <= 0:
        return INF
    # instances.log 里 source_length / prediction_length 常见是秒；delays 是 ms
    if v < 1e4:
        return v * 1000.0
    return v


# ============================================================
def _fix_decimal_for_segale_text(s: str) -> str:
    """
    只修 segale 里常见的小数拆分：
      "84. 22" / "84 .22" / "84 . 22"  -> "84.22"
    不改其它标点/空格/分词规则。
    """
    s = _norm(s)
    return re.sub(r"(?<=\d)\s*\.\s*(?=\d)", ".", s)


# 统一字符形态
def _norm(s: str) -> str:
    """Unicode 归一化：把全角半角、兼容字符统一（NFKC 常用）。"""
    return unicodedata.normalize("NFKC", s or "")


def _find_sublist(hay: List[str], needle: List[str], start: int) -> Optional[Tuple[int, int]]:
    """
    在 hay[start:] 里找 needle 的连续匹配，返回 (s, e) half-open。
    举例：hay=[a,b,c,d], needle=[c,d] -> 返回 (2,4)
    """
    if not needle:
        return None
    n = len(needle)
    # i 的上界要保证 hay[i:i+n] 不越界
    for i in range(start, max(start, len(hay) - n) + 1):
        if hay[i:i + n] == needle:  # 👈 会不会严格了点？？？
            return i, i + n
    return None


# ============================================================
# instances.log (第 n 个 对应的是第 n 个 音频): 
    # {index: 0, source: src1_wav_path, prediction: tgt_hyp_wav_path, delays: 时间无标点ms, durations: 时间无标点ms, intervals：时间无标点ms， elapsed: 时间无标点ms, prediction_length: tgt_hyp_wav时间长度s, reference: src1_wav_path, source_length: src1_wav时间长度s, prediction_text: tgt_hyp_text有标点, ...}
    # {index: N-1, source: srcN_wav_path, prediction: tgt_hyp_wav_path, delays: 时间无标点ms, durations: 时间无标点ms, intervals：时间无标点ms， elapsed: 时间无标点ms, prediction_length: tgt_hyp_wav时间长度s, reference: srcN_wav_path, source_length: srcN_wav时间长度s, prediction_text: tgt_hyp_text有有标点, ...}
def _load_instances_log(instances_log: str) -> Dict[str, Dict[str, Any]]:
    """
    读取 SimulEval 产生的 instances.log（jsonl）：
    返回 dict: doc_id(basename wav) -> instance_record

    你在这里做了几件重要的“对齐清洗”：
    - doc_id 用 source 路径 basename 得到（跨平台替换 \\）
    - delays/durations/elapsed/intervals 全取出来
    - 如果 elapsed 缺失或长度和 delays 不一致，就用 delays 代替
    - 最后统一截断到相同长度 m，避免下游切片炸
    """
    mp = {}
    with open(instances_log, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            h = json.loads(line)

            # source 字段可能是 list 或 str：取 basename 当 doc_id
            src = h.get("source")
            src_path = (src[0] if isinstance(src, list) else src) or ""
            doc_id = os.path.basename(str(src_path)).replace("\\", "/")

            # delays/durations/elapsed/intervals 都应该是 “unit 无标点” 的序列
            # 这些序列应该是一一对应的“输出 unit 级别”时间信息
            delays = h.get("delays") or []
            durations = h.get("durations") or []
            elapsed = h.get("elapsed") or []
            intervals = h.get("intervals") or []

            # elapsed 缺失就用 delays
            if (not elapsed) or (len(elapsed) != len(delays)):
                elapsed = list(delays)

            # 统一长度（以 delays 和 elapsed 的最短为准）
            m = min(len(delays), len(elapsed))
            delays = list(delays[:m])
            elapsed = list(elapsed[:m])
            if durations:
                durations = list(durations[:m])
            if intervals:
                intervals = list(intervals[:m])

            # 存一些你后面会用到的派生字段
            h["_doc_id"] = doc_id
            h["_source_length_ms"] = _to_ms(h.get("source_length", INF))

            h["_delays"] = delays
            h["_durations"] = durations
            h["_elapsed"] = elapsed
            h["_intervals"] = intervals

            mp[doc_id] = h
    return mp  # {doc_id: {<instance>, _doc_id, _source_length_ms, _delays, _durations, _elapsed, _intervals}}


# asr/asr1.json ... asrN.json: 
    # {src: src1_wav_path, tgt: tgt_hyp_wav_path, text: tgt_hyp_text有标点, time_stamps: [{text: unit无标点, start_time: 时间s, end_time: 时间s}, ...]}
    # {src: srcN_wav_path, tgt: tgt_hyp_wav_path, text: tgt_hyp_text有标点, time_stamps: [{text: unit无标点, start_time: 时间s, end_time: 时间s}, ...]}
def _load_asr_units(asr_dir: str) -> Dict[str, List[str]]:
    """
    读取 asr_dir 里每条音频对应的 ASR json（你说里面有 time_stamps 或 time_stamps_with_gap）：
    返回 dict: doc_id(basename wav) -> units(list[str])

    核心：把 time_stamps 的 text 拼成 unit 序列（用 _tokenize_mixed_units）
    这样能和 delays 的 unit 数量/顺序对应起来（理论上）。
    """
    mp = {}
    for fn in os.listdir(asr_dir):  # asr 文件夹
        if not fn.endswith(".json"):
            continue
        path = os.path.join(asr_dir, fn)
        try:
            with open(path, "r", encoding="utf-8") as f:
                d = json.load(f)
        except Exception:
            continue
        src = d.get("src") or ""
        doc_id = os.path.basename(str(src)).replace("\\", "/")  # doc_id
        ts = d.get("time_stamps") or d.get("time_stamps_with_gap") or []  # time_stamps
        units = []
        for x in ts:
            u = _norm(x.get("text", ""))
            if not u:
                continue
            # asr 的 unit 理论上已“无标点”，这里保险再去一次
            units.extend(_qwen_units(u, "chinese"))
        mp[doc_id] = units
    return mp  # {doc_id: [unit1, unit2, ...]}


# segale.jsonl (分段对齐)：
    # {"doc_id": src1_wav_basename, "seg_id": 1, "sys_id": null, "src":  src_text_seg, "tgt": tgt_hyp_text_seg, "ref": tgt_ref_text_seg}
    # {"doc_id": src1_wav_basename, "seg_id": 2, "sys_id": null, "src":  src_text_seg, "tgt": tgt_hyp_text_seg, "ref": tgt_ref_text_seg}
    # {"doc_id": src1_wav_basename, "seg_id": a, "sys_id": null, "src":  src_text_seg, "tgt": tgt_hyp_text_seg, "ref": tgt_ref_text_seg}
    # {"doc_id": srcN_wav_basename, "seg_id": 1, "sys_id": null, "src":  src_text_seg, "tgt": tgt_hyp_text_seg, "ref": tgt_ref_text_seg}
def _load_segale(segale_jsonl: str) -> Dict[str, List[Dict[str, Any]]]:
    """
    读取 segale 对齐结果（jsonl）：
    返回 dict: doc_id -> list[segale_line], 按 seg_id 升序

    你后面会按顺序处理 segments，所以这里排序很关键。
    """
    mp: Dict[str, List[Dict[str, Any]]] = {}
    with open(segale_jsonl, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            r = json.loads(line)
            doc_id = r["doc_id"]
            mp.setdefault(doc_id, []).append(r)
    # seg_id 可能是 int，也可能是字符串；尽量按出现顺序 + 数字优先；非数字放最后
    for k in mp:
        mp[k].sort(key=lambda x: int(x["seg_id"]) if str(x["seg_id"]).isdigit() else 10**9)
    return mp  # {doc_id: [seg_id1, seg_id2, ...]}


# ref_segments.yaml (第 i 个 对应的是第 i 个句子) src speech 的时间信息: 
    # {duration: 时间s, offset: 时间s, speaker_id: xxx, wav: src1_wav_basename}
    # {duration: 时间s, offset: 时间s, speaker_id: xxx, wav: src1_wav_basename}
    # {duration: 时间s, offset: 时间s, speaker_id: xxx, wav: srcN_wav_basename}
# source.txt (第 i 行 对应的是第 i 个句子，行和ref_segments.yaml的行绑定): 
    # src1 sentence1 \n src1 sentence_b \n srcN sentence1
def _load_yaml_and_source_sentences(yaml_file: str, source_txt: str) -> Dict[str, List[Tuple[int, float, float, List[str]]]]:
    """
    读 ref_segments.yaml + source.txt（行对齐）：
    返回 dict: doc_id -> list of tuples per sentence:
      (sent_idx_global, offset_ms, end_ms, src_tokens)

    yaml 每行通常含：
    - wav: doc_id（wav 文件名）
    - offset: 句子起点（秒）
    - duration: 句子时长（秒）
    你在这里把 offset/duration 转成毫秒，且把 source.txt 行切成 tokens。
    """
    with open(yaml_file, "r", encoding="utf-8") as f:
        segs = yaml.safe_load(f) or []
    with open(source_txt, "r", encoding="utf-8") as f:
        src_lines = [x.rstrip("\n") for x in f]

    # 强制要求 yaml 行数与 source.txt 行数一致（对齐假设）
    assert len(segs) == len(src_lines), "ref_segments.yaml 行数 必须 == source.txt 行数"

    mp: Dict[str, List[Tuple[int, float, float, List[str]]]] = {}
    for i, (seg, sline) in enumerate(zip(segs, src_lines)):
        doc_id = seg["wav"]
        off_ms = float(seg["offset"]) * 1000.0
        dur_ms = float(seg["duration"]) * 1000.0
        end_ms = off_ms + dur_ms
        toks = _qwen_units(sline, "english")
        mp.setdefault(doc_id, []).append((i, off_ms, end_ms, toks))
    return mp  # {doc_id: [(sent_idx_global, offset_ms, end_ms, src_tokens), ...]}


# ============================================================
# 把一个 segale 的 segment（segale.src）映射到 source.txt 的哪些句子，从而得到这个 segment 在源音频里的时间范围（start_ms, end_ms）
# 这里假设 segale_src_seg = src_sent j + src_sent j+1 + ...
def _match_src_span_for_seg(segale_src_seg: str,
                            src_sent_list: List[Tuple[int, float, float, List[str]]],
                            list_j: int) -> Tuple[int, int, float, float]:
    """
    用 segale.src 去 source.txt(按句)里“顺序匹配”，确定该 segment 的源时间跨度：
    返回: (new_cursor_sent, num_sent_used, start_ms, end_ms)

    核心思想：
    - segale.src 代表该 segment 对应的源文本片段（通常等于若干句的拼接）
    - 你从 cursor_sent 开始累加句子的 tokens，直到累计 tokens == target tokens（严格相等）
    - 一旦相等，就用第一个句子的 offset 作为 start_ms，用最后一句的 end_ms 作为 end_ms

    ⚠️ 假设非常强：必须严格 token 串相等（标点已去掉）；
       只要出现轻微差异（例如缩写/大小写/分词差），就会走退化策略。
    """
    target = _qwen_units(segale_src_seg, "english")  # Hi, this is Elena. I'm going to xxx. -> [hi, this, is, elena, i, m, going, to, xxx]
    # ---------------------------------------------------\
    if not target:
        # 空 src：退化成“用当前句的时间范围”
        _, s_ms, e_ms, _ = src_sent_list[list_j]
        return list_j + 1, 1, s_ms, e_ms
    # ---------------------------------------------------/
    acc: List[str] = []
    start_ms = None
    end_ms = None
    used = 0
    j = list_j

    # 顺序累加句子直到 token 串等于 target（严格）
    while j < len(src_sent_list):
        _, s_ms, e_ms, toks = src_sent_list[j]  # (j, start, end, [hi, this, is, elena]), (j+1, start, end, [i, m, going, to, xxx])
        if start_ms is None:
            start_ms = s_ms
        end_ms = e_ms
        acc.extend(toks)
        used += 1
        
        if acc == target:
            return j + 1, used, float(start_ms), float(end_ms)

        # ---------------------------------------------------\
        # 如果 acc 已经比 target 长，还没等于，就失败：退化用 1 句
        if len(acc) > len(target) and target:
            break
        # ---------------------------------------------------/
        j += 1

    # ---------------------------------------------------\
    # 退化策略：用 1 句
    _, s_ms, e_ms, _ = src_sent_list[list_j]
    return list_j + 1, 1, float(s_ms), float(e_ms)
    # ---------------------------------------------------/

# 假设 segale_tgt_seg = n * tgt_asr_unit
def _match_tgt_units_for_seg(segale_tgt_seg: str,
                            tgt_asr_units: List[str],
                            unit_i: int,
                            doc_id: str,
                            seg_id: str) -> Tuple[int, int, int]:
    """
    用 segale.tgt（去标点后 tokenized）在 asr_units 里“顺序找连续子串”：
    返回 (new_cursor_unit, u_start, u_end)

    - cursor_unit 保证整体是单调前进的（避免跨段乱匹配）
    - 找不到就退化为空段： (cursor, cursor, cursor)

    ⚠️ 强假设：segale.tgt token 序列必须在 asr_units 里出现为连续子串
       否则该 segment 会在后面被 skip（因为 seg_delays 为空）。
    """

    segale_tgt_seg = _fix_decimal_for_segale_text(segale_tgt_seg)   # ✅ 只修 84. 22
    needle = _qwen_units(segale_tgt_seg, "chinese")  # 嗨，我是丽娜。我将xxx。 -> [嗨, 我, 是, 丽, 娜, 我, 将, xxx]
    # ---------------------------------------------------\
    if not needle:
        return unit_i, unit_i, unit_i
    # ---------------------------------------------------/

    # asr_units: [嗨, 我, 是, 丽, 娜, 我, 将, xxx, ......]
    hit = _find_sublist(tgt_asr_units, needle, unit_i)
    # ---------------------------------------------------\
    if hit is None:
        logger.warning(
            "[skip][tgt-not-found] doc=%s seg_id=%s cursor=%d needle_len=%d needle=%s asr_ctx=%s",
            doc_id, seg_id, unit_i,
            len(needle), needle[:20],
            tgt_asr_units[unit_i: min(len(tgt_asr_units), unit_i + 60)]
        )
        # 找不到：退化为空
        return unit_i, unit_i, unit_i
    # ---------------------------------------------------/
    u_start, u_end = hit
    return u_end, u_start, u_end


# ============================================================
# 新的 resegment：不对齐，只计算 YAAL（segment-level）
# ============================================================
# 问题1：
# {
#   "doc_id": "2022.acl-long.268.wav", 
#   "sys_id": null, 
#   "src": "The best result that we got was eighty four point twenty two, which is the highest across all the models that we tried on the test set.", 
#   "ref": "我们得到的最好结果是84.22分，这是我们在测试集上尝试的所有模型中最高的分数。", 
#   "tgt": "我们得到的最佳结果是 84. 22，这是我们尝试的所有模型中最高的。", 
#   "seg_id": 73
# }
# {
#     "text": "8422",
#     "start_time": 562.998,
#     "end_time": 563.638
# }

# 问题2：
# 中文标点
# -----------------------------------
def resegment(
    yaml_file: str,
    source_sentences_file: str,   # ✅ 用 source.txt 来确定 seg 的源时间跨度
    instances_log: str,           # ✅ 用 delays/durations/elapsed
    segale_file: str,             # ✅ 你已经对齐好的 segale.jsonl
    asr_dir: str,                 # ✅ 用 time_stamps(text) 把 tgt 映射到 unit 下标
    output_folder: str,
    bleu_tokenizer: str,
):
    """
    主流程：把“全音频的 unit-level delays”切成“segment-level delays”，然后算 segment-level YAAL。

    输入：
    - segale：给你 segment 切分的 src/tgt（以及 seg_id、doc_id）
    - yaml + source.txt：给你源句子的 offset/duration，用来定位 segment 的源时间范围（start_ms/end_ms）
    - instances.log：给你全音频的 delays/elapsed（unit-level 时间）
    - asr_dir：给你全音频的 asr unit 序列，用来把 segment tgt 映射到全音频 unit 下标区间

    输出：
    - instances.resegmented.json：每个 segment 一个 instance（含切出来的 delays）
    - scores.resegmented.csv：平均 YAAL/CA-YAAL（以及 BLEU=0/可忽略）
    """
    os.makedirs(output_folder, exist_ok=True)

    # 1) load data
    segale_by_doc = _load_segale(segale_file)
    inst_by_doc = _load_instances_log(instances_log)
    asr_units_by_doc = _load_asr_units(asr_dir)
    sent_by_doc = _load_yaml_and_source_sentences(yaml_file, source_sentences_file)

    # 2) build per-seg instances
    instances: List[Instance] = []
    instances_dict: List[Dict[str, Any]] = []

    global_idx = 0
    for doc_id, segs in segale_by_doc.items():
        # 数据缺失就跳过该 doc
        if doc_id not in inst_by_doc:
            logger.warning(f"[skip] doc missing in instances.log: {doc_id}")
            continue
        if doc_id not in asr_units_by_doc:
            logger.warning(f"[skip] doc missing in asr_dir: {doc_id}")
            continue
        if doc_id not in sent_by_doc:
            logger.warning(f"[skip] doc missing in yaml/source.txt: {doc_id}")
            continue

        inst = inst_by_doc[doc_id]
        delays_all = inst["_delays"]
        durations_all = inst["_durations"]
        elapsed_all = inst["_elapsed"]

        asr_units = asr_units_by_doc[doc_id]

        # 强一致性检查：ASR unit 数应当和 delays unit 数对应
        # 对不上说明你的 pipeline 产物不一致：这里用 min 截断保命
        m = min(len(asr_units), len(delays_all), len(elapsed_all))
        if len(asr_units) != len(delays_all):
            logger.warning(
                f"[warn] unit count mismatch for {doc_id}: "
                f"asr_units={len(asr_units)} vs delays={len(delays_all)}. trunc to {m}."
            )
            asr_units = asr_units[:m]
            delays_all = delays_all[:m]
            elapsed_all = elapsed_all[:m]
            if durations_all:
                durations_all = durations_all[:m]

        # 3) sequential cursors
        cursor_unit = 0
        cursor_sent = 0

        doc_sent_list = sent_by_doc[doc_id]

        for seg in segs:
            seg_src = seg.get("src", "")
            seg_tgt = seg.get("tgt", "")
            seg_ref = seg.get("ref", "")

            # 3.1 用 seg_src 在 source.txt 里顺序匹配，得到该 segment 的源时间范围
            cursor_sent, _, seg_start_ms, seg_end_ms = _match_src_span_for_seg(
                seg_src, doc_sent_list, cursor_sent
            )
            # 该 segment 的源长度（ms），至少为 1ms 防止除零/异常
            seg_source_len_ms = max(1.0, seg_end_ms - seg_start_ms)

            # 3.2 用 seg_tgt 在 asr_units 里找连续子串，得到 unit 区间 [u_start, u_end)
            cursor_unit, u_start, u_end = _match_tgt_units_for_seg(
                seg_tgt, asr_units, cursor_unit,
                doc_id=doc_id, seg_id=seg.get("seg_id")
            )

            # 从全音频 delays/elapsed 切出这个 segment 的 unit 时间序列
            seg_delays = delays_all[u_start:u_end]
            seg_elapsed = elapsed_all[u_start:u_end]

            # 如果这段匹配不到 unit，就跳过（否则 YAAL 没意义）
            if not seg_delays:
                logger.warning(
                    "[skip][empty-matched-units] doc=%s seg_id=%s cursor_unit=%d u_start=%d u_end=%d "
                    "len(asr_units)=%d len(delays_all)=%d len(elapsed_all)=%d seg_tgt_len=%d",
                    doc_id, seg.get("seg_id"),
                    cursor_unit, u_start, u_end,
                    len(asr_units), len(delays_all), len(elapsed_all),
                    len((seg_tgt or "").strip()),
                )
                continue

            # 3.3 把 delays/elapsed 变为“相对 segment 起点”的时间
            # 因为 delays 是相对整条音频起点，所以要减 seg_start_ms
            seg_delays_rel = [max(0.0, float(d) - seg_start_ms) for d in seg_delays]
            seg_elapsed_rel = [max(0.0, float(e) - seg_start_ms) for e in seg_elapsed]

            # 构造一个新的 segment-level instance record
            new_seg_dict = {
                "index": global_idx,
                "doc_id": doc_id,
                "seg_id": seg.get("seg_id"),

                # prediction/reference 主要为了格式完整；YAAL 不用文本
                "prediction": seg.get("tgt", ""),   # 只是占位；YAAL 不用文本
                "reference": seg_ref,     # ✅ 写真实 reference 文本，BLEU 要用
                
                # YAAL 的“源长度”：这里用 segment 音频时长（ms）
                "source_length": seg_source_len_ms,

                # unit-level 时间戳序列（相对 segment 起点）
                "delays": seg_delays_rel,
                "elapsed": seg_elapsed_rel,

                # longform 截断用：segment 内的 recording_end
                "recording_end": seg_source_len_ms,  # segment 内的 recording_end
                
                # 下面这些只是为了 debug/可追溯（不影响指标）
                "_u_start": u_start,
                "_u_end": u_end,
                "_seg_start_ms": seg_start_ms,
                "_seg_end_ms": seg_end_ms,
                "_ref_text": seg_ref,
                "_src_text": seg_src,
            }
            instances_dict.append(new_seg_dict)

            # 注意：这里 latency_unit="word" 其实不重要，
            # 因为 reference=None 时，YAAL 用的是 len(delays) 作为 tgt_len
            instances.append(
                Instance(new_seg_dict, latency_unit="word")
            )

            global_idx += 1

    # 4) write instances + scores
    with open(
        os.path.join(output_folder, "instances.resegmented.json"), "w", encoding="utf-8"
    ) as f:
        f.write(json.dumps(instances_dict, ensure_ascii=False, indent=2) + "\n")

    scores = evaluate_instances(instances, bleu_tokenizer)
    with open(
        os.path.join(output_folder, "scores.resegmented.csv"), "w", encoding="utf-8"
    ) as f:
        f.write("\t".join(scores.keys()) + "\n")
        f.write("\t".join([f"{v:.4f}" for v in scores.values()]) + "\n")

    logger.info(f"Done. segments={len(instances)}. Output -> {output_folder}")


# ============================================================
# CLI
# ============================================================
if __name__ == "__main__":
    # parser = ArgumentParser(description="Compute YAAL on SEGALE segments for S2S (unit-level)")

    # parser.add_argument("--yaml_file", type=str, required=True, help="ref_segments.yaml")
    # parser.add_argument("--source_sentences_file", type=str, required=True, help="source.txt (line-aligned to yaml)")
    # parser.add_argument("--instances_log", type=str, required=True, help="instances.log")
    # parser.add_argument("--segale_file", type=str, required=True, help="segale.jsonl")
    # parser.add_argument("--asr_dir", type=str, required=True, help="dir contains asr/*.json with time_stamps")
    # parser.add_argument("--output_folder", type=str, required=True, help="output folder")
    # parser.add_argument("--bleu_tokenizer", type=str, default="13a", help="Tokenizer for BLEU scorer (optional)")

    # args = parser.parse_args()

    # resegment(
    #     yaml_file=args.yaml_file,
    #     source_sentences_file=args.source_sentences_file,
    #     instances_log=args.instances_log,
    #     segale_file=args.segale_file,
    #     asr_dir=args.asr_dir,
    #     output_folder=args.output_folder,
    #     bleu_tokenizer=args.bleu_tokenizer,
    # )

    yaml_file = "data/input/ACL.ACLdev2023.en-xx.gold_segments.yaml"
    source_sentences_file = "data/input/ACL.6060.dev.en-xx.en.txt"
    instances_log = "data/output_qwen_asr3/instances.log"
    segale_file = "data/output_segale3/hyp/aligned_spacy_hyp.jsonl"
    asr_dir = "data/output_qwen_asr3"
    output_folder = "data/output_longyaal3"
    bleu_tokenizer = "zh"

    resegment(
        yaml_file=yaml_file,
        source_sentences_file=source_sentences_file,
        instances_log=instances_log,
        segale_file=segale_file,
        asr_dir=asr_dir,
        output_folder=output_folder,
        bleu_tokenizer=bleu_tokenizer,
    )