# -*- coding: utf-8 -*-

import logging
import re
from statistics import mean
from typing import List, Dict, Any, Tuple, Optional

from sacrebleu.metrics.bleu import BLEU
from argparse import ArgumentParser

import unicodedata
import yaml
import json
import os

from dataclasses import dataclass

from pipeline_qwen3_forcealign_tokenizer2 import Qwen3ForceAlignTokenizer

qwen_tok = Qwen3ForceAlignTokenizer()


def _norm(s: str) -> str:
    return unicodedata.normalize("NFKC", s or "")


def _qwen_units(text: str, language: str) -> List[str]:
    return qwen_tok.encode_timestamp(_norm(text), language)


logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

INF = float("inf")


# ============================================================
# 原样保留：Instance / BLEU / YAAL
# ============================================================
class Instance:
    """
    Stores the information about the output instances generated by SimulEval.
    """

    def __init__(self, info: Dict[str, Any], latency_unit: str = "word"):
        for key, value in info.items():
            setattr(self, key, value)

        self.reference = info.get("reference", "")
        self.prediction = info.get("prediction", "")
        self.latency_unit = latency_unit
        self.metrics = {}

    @property
    def reference_length(self) -> int:
        return self.string_to_len(self.reference, self.latency_unit)

    @staticmethod
    def string_to_len(string: str, latency_unit: str) -> int:
        if latency_unit == "word":
            return len(string.split(" "))
        elif latency_unit == "char":
            return len(string.strip())
        else:
            raise ValueError(f"Unknown latency unit: {latency_unit}")


class SacreBLEUScorer:
    def __init__(self, tokenizer: str = "13a") -> None:
        super().__init__()
        self.logger = logging.getLogger("simuleval.scorer.bleu")
        self.tokenizer = tokenizer

    def __call__(self, instances: Dict) -> float:
        try:
            return (
                BLEU(tokenize=self.tokenizer)
                .corpus_score(
                    [ins.prediction for ins in instances.values()],
                    [[ins.reference for ins in instances.values()]],
                )
                .score
            )
        except Exception as e:
            self.logger.error(str(e))
            return 0.0


class YAALScorer:
    r"""
    YAAL / CA-YAAL
    """

    def __init__(
        self,
        computation_aware: bool = False,
        is_longform: bool = False,
        force_unit_target_len: bool = True,
    ):
        self.computation_aware = computation_aware
        self.is_longform = is_longform
        self.force_unit_target_len = force_unit_target_len

    def get_delays_lengths(self, ins: Instance):
        timestamp_type = "delays" if not self.computation_aware else "elapsed"
        delays = getattr(ins, timestamp_type, None)
        assert delays

        src_len = ins.source_length
        if self.force_unit_target_len:
            tgt_len = len(delays)
        else:
            tgt_len = ins.reference_length
        return delays, src_len, tgt_len

    def compute(self, ins: Instance):
        delays, source_length, target_length = self.get_delays_lengths(ins)

        is_longform = hasattr(ins, "longform") or self.is_longform
        recording_end = (
            ins.recording_end if hasattr(ins, "recording_end") else float("inf")
        )

        if (delays[0] >= source_length and not is_longform) or (
            delays[0] >= recording_end
        ):
            return None

        laal = 0.0
        gamma = max(len(delays), target_length) / source_length
        tau = 0

        for t_minus_1, d in enumerate(delays):
            if (d >= source_length and not is_longform) or (d >= recording_end):
                break
            laal += d - t_minus_1 / gamma
            tau = t_minus_1 + 1

        if tau == 0:
            return None
        laal /= tau
        return laal

    def __call__(self, instances: Dict[int, Instance]) -> float:
        scores = []
        timestamp_type = "elapsed" if self.computation_aware else "delays"
        for index, ins in instances.items():
            delays = getattr(ins, timestamp_type, None)
            if delays is None or len(delays) == 0:
                logger.warning(f"Instance {index} has no delay information. Skipped")
                continue
            score = self.compute(ins)
            if score is None:
                continue
            scores.append(score)

        return mean(scores) if len(scores) > 0 else float("nan")


def evaluate_instances(
    resegmented_instances: List[Instance], tokenizer: str
) -> Dict[str, float]:
    ca_unaware_yaal_scorer = YAALScorer(is_longform=True, force_unit_target_len=True)
    ca_aware_yaal_scorer = YAALScorer(
        computation_aware=True, is_longform=True, force_unit_target_len=True
    )
    bleu_scorer = SacreBLEUScorer(tokenizer)

    resegmented_instances_dict = {i: ins for i, ins in enumerate(resegmented_instances)}
    ca_unaware_yaal_score = ca_unaware_yaal_scorer(resegmented_instances_dict)
    ca_aware_yaal_score = ca_aware_yaal_scorer(resegmented_instances_dict)
    bleu_score = bleu_scorer(resegmented_instances_dict)

    return {
        "ca_unaware_yaal": ca_unaware_yaal_score,
        "ca_aware_yaal": ca_aware_yaal_score,
        "bleu": bleu_score,
    }


# ============================================================
# 工具函数
# ============================================================
def _to_ms(x: Any) -> float:
    if x is None:
        return INF
    try:
        v = float(x)
    except Exception:
        return INF
    if v <= 0:
        return INF
    if v < 1e4:
        return v * 1000.0
    return v


def _fix_decimal_for_segale_text(s: str) -> str:
    """
    "84. 22" / "84 .22" / "84 . 22" -> "84.22"
    """
    s = _norm(s)
    return re.sub(r"(?<=\d)\s*\.\s*(?=\d)", ".", s)


def _normalize_token_for_match(tok: str) -> str:
    """
    用于匹配时的 token 归一化：
    - NFKC
    - lower
    - 去掉标点 / 空白 / 控制字符
    """
    s = _norm(tok).lower().strip()
    out = []
    for ch in s:
        cat = unicodedata.category(ch)
        if cat[0] in ("P", "Z", "C"):
            continue
        out.append(ch)
    return "".join(out)


def _is_latin_token(tok: str) -> bool:
    tok = (tok or "").strip()
    if not tok:
        return False
    return all(0x20 <= ord(c) < 0x4E00 for c in tok)


# def _token_match_loose(n_tok: str, h_tok: str) -> bool:
#     n = (n_tok or "").strip()
#     h = (h_tok or "").strip()
#     if not n:
#         return True
#     if n == h or h.startswith(n):
#         return True

#     n_norm = _normalize_token_for_match(n)
#     h_norm = _normalize_token_for_match(h)
#     if not n_norm:
#         return True

#     return (
#         n_norm == h_norm
#         or h_norm.startswith(n_norm)
#         or n_norm.startswith(h_norm)
#     )
def _token_match_loose(n_tok: str, h_tok: str) -> bool:
    """
    更保守的 loose match：
    - 优先 exact / normalized exact
    - 对一般 token 不再随便用 startswith，避免把
      'transformer' 和 'transformerbased' 提前误判成 1:1
    - 只给 very short latin token 保留一点前缀容错（如 QED vs QEDQED）
    """
    n = (n_tok or "").strip()
    h = (h_tok or "").strip()
    if not n:
        return True

    if n == h:
        return True

    n_norm = _normalize_token_for_match(n)
    h_norm = _normalize_token_for_match(h)
    if not n_norm:
        return True

    if n_norm == h_norm:
        return True

    # 只对很短的拉丁 token 允许前缀容错，避免误吞 merge 场景
    if _is_latin_token(n) and _is_latin_token(h):
        if len(n_norm) <= 4 and len(h_norm) <= 12:
            if h_norm.startswith(n_norm) or n_norm.startswith(h_norm):
                return True

    return False


def _find_sublist(
    hay: List[str], needle: List[str], start: int
) -> Optional[Tuple[int, int]]:
    if not needle:
        return None
    if start >= len(hay):
        return None
    n = len(needle)
    for i in range(start, max(start, len(hay) - n) + 1):
        if hay[i:i + n] == needle:
            return i, i + n
    return None


def _find_sublist_loose(
    hay: List[str], needle: List[str], start: int
) -> Optional[Tuple[int, int]]:
    if not needle:
        return None
    if start >= len(hay):
        return None
    n = len(needle)
    for i in range(start, max(start, len(hay) - n) + 1):
        ok = True
        for k in range(n):
            if not _token_match_loose(needle[k], hay[i + k]):
                ok = False
                break
        if ok:
            return i, i + n
    return None


def _concat_norm(tokens: List[str]) -> str:
    return "".join(_normalize_token_for_match(t) for t in tokens if t is not None)


# def _try_align_from_start(
#     hay_norm: List[str],
#     needle_norm: List[str],
#     start_i: int,
#     max_hay_skip: int = 2,
#     max_needle_skip: int = 1,
# ) -> Optional[Tuple[int, int, float, int, int]]:
#     """
#     从 hay[start_i] 开始，做一个“顺序、受限”的对齐：
#     - 1:1
#     - 2(needle):1(hay)
#     - 1(needle):2(hay)
#     - 少量 skip
#     返回 (u_start, u_end, score, matched_needle_count, consumed_hay_count)
#     只有在“needle 全部吃完”时才返回。
#     """
#     j = start_i
#     k = 0
#     used_hay_skip = 0
#     used_needle_skip = 0
#     matched_needle = 0

#     while k < len(needle_norm) and j < len(hay_norm):
#         hn = hay_norm[j]
#         nn = needle_norm[k]

#         # 跳过空规范 token（不计匹配）
#         if not hn:
#             j += 1
#             continue
#         if not nn:
#             k += 1
#             continue

#         # 1:1
#         if hn == nn or hn.startswith(nn) or nn.startswith(hn):
#             j += 1
#             k += 1
#             matched_needle += 1
#             continue

#         # 2 needle -> 1 hay
#         if k + 1 < len(needle_norm):
#             nn2 = needle_norm[k] + needle_norm[k + 1]
#             if nn2 and (hn == nn2 or hn.startswith(nn2) or nn2.startswith(hn)):
#                 j += 1
#                 k += 2
#                 matched_needle += 2
#                 continue

#         # 1 needle -> 2 hay
#         if j + 1 < len(hay_norm):
#             hn2 = hay_norm[j] + hay_norm[j + 1]
#             if hn2 and (hn2 == nn or hn2.startswith(nn) or nn.startswith(hn2)):
#                 j += 2
#                 k += 1
#                 matched_needle += 1
#                 continue

#         # skip 一个 hay token
#         if used_hay_skip < max_hay_skip:
#             used_hay_skip += 1
#             j += 1
#             continue

#         # skip 一个 needle token
#         if used_needle_skip < max_needle_skip:
#             used_needle_skip += 1
#             k += 1
#             continue

#         break

#     # 末尾继续吞掉空 needle_norm
#     while k < len(needle_norm) and not needle_norm[k]:
#         k += 1

#     if k < len(needle_norm):
#         return None

#     consumed_hay = max(1, j - start_i)
#     denom = max(len([x for x in needle_norm if x]), consumed_hay)
#     score = matched_needle / max(1, denom)
#     return start_i, j, score, matched_needle, consumed_hay

def _try_align_from_start(
    hay_norm: List[str],
    needle_norm: List[str],
    start_i: int,
    max_hay_skip: int = 3,
    max_needle_skip: int = 2,
) -> Optional[Tuple[int, int, float, int, int]]:
    """
    从 hay[start_i] 开始，做顺序受限对齐：
    优先级：
      1) exact 1:1
      2) 2 needle -> 1 hay
      3) 1 needle -> 2 hay
      4) loose/prefix 1:1
      5) 少量 skip
    """
    j = start_i
    k = 0
    used_hay_skip = 0
    used_needle_skip = 0
    matched_needle = 0

    while k < len(needle_norm) and j < len(hay_norm):
        hn = hay_norm[j]
        nn = needle_norm[k]

        if not hn:
            j += 1
            continue
        if not nn:
            k += 1
            continue

        # --------------------------------------------------
        # 1) exact 1:1
        # --------------------------------------------------
        if hn == nn:
            j += 1
            k += 1
            matched_needle += 1
            continue

        # --------------------------------------------------
        # 2) 2 needle -> 1 hay
        #    transformer + based -> transformerbased
        # --------------------------------------------------
        if k + 1 < len(needle_norm):
            nn2 = needle_norm[k] + needle_norm[k + 1]
            if nn2 and hn == nn2:
                j += 1
                k += 2
                matched_needle += 2
                continue

        # --------------------------------------------------
        # 3) 1 needle -> 2 hay
        # --------------------------------------------------
        if j + 1 < len(hay_norm):
            hn2 = hay_norm[j] + hay_norm[j + 1]
            if hn2 and hn2 == nn:
                j += 2
                k += 1
                matched_needle += 1
                continue

        # --------------------------------------------------
        # 4) loose/prefix 1:1
        #    放到 merge/split 后面，避免误吞
        # --------------------------------------------------
        if hn.startswith(nn) or nn.startswith(hn):
            # 对很长 token，prefix 太危险，限制一下长度差
            if abs(len(hn) - len(nn)) <= 2:
                j += 1
                k += 1
                matched_needle += 1
                continue

        # --------------------------------------------------
        # 5) 更宽一点的 merge/split
        # --------------------------------------------------
        if k + 1 < len(needle_norm):
            nn2 = needle_norm[k] + needle_norm[k + 1]
            if nn2 and (hn.startswith(nn2) or nn2.startswith(hn)):
                if abs(len(hn) - len(nn2)) <= 2:
                    j += 1
                    k += 2
                    matched_needle += 2
                    continue

        if j + 1 < len(hay_norm):
            hn2 = hay_norm[j] + hay_norm[j + 1]
            if hn2 and (hn2.startswith(nn) or nn.startswith(hn2)):
                if abs(len(hn2) - len(nn)) <= 2:
                    j += 2
                    k += 1
                    matched_needle += 1
                    continue

        # --------------------------------------------------
        # 6) skip
        # --------------------------------------------------
        if used_hay_skip < max_hay_skip:
            used_hay_skip += 1
            j += 1
            continue

        if used_needle_skip < max_needle_skip:
            used_needle_skip += 1
            k += 1
            continue

        break

    while k < len(needle_norm) and not needle_norm[k]:
        k += 1

    if k < len(needle_norm):
        return None

    consumed_hay = max(1, j - start_i)
    non_empty_needle = len([x for x in needle_norm if x])
    denom = max(non_empty_needle, consumed_hay)
    score = matched_needle / max(1, denom)

    return start_i, j, score, matched_needle, consumed_hay


def _find_sublist_merge_split_window(
    hay: List[str],
    needle: List[str],
    start: int,
    # window_size: int = 220,
    # min_score: float = 0.90,
    # max_hay_skip: int = 2,
    # max_needle_skip: int = 1,
    # max_start_drift: int = 160,
    window_size=280,
    min_score=0.86,
    max_hay_skip=3,
    max_needle_skip=2,
    max_start_drift=180,
) -> Optional[Tuple[int, int, float]]:
    """
    在 hay[start : start+window_size] 内，找一个更稳的局部对齐：
    - 顺序匹配
    - 支持 1:1 / 2:1 / 1:2
    - 允许少量 skip
    - 必须把 needle 基本吃完
    """
    if not hay or not needle or start >= len(hay):
        return None

    hay_norm = [_normalize_token_for_match(x) for x in hay]
    needle_norm = [_normalize_token_for_match(x) for x in needle]

    best = None
    scan_end = min(len(hay), start + window_size)

    for i in range(start, scan_end):
        if i - start > max_start_drift:
            break

        res = _try_align_from_start(
            hay_norm,
            needle_norm,
            i,
            max_hay_skip=max_hay_skip,
            max_needle_skip=max_needle_skip,
        )
        if res is None:
            continue

        s, e, score, matched_needle, consumed_hay = res

        # 再加一些安全阀
        non_empty_needle = len([x for x in needle_norm if x])
        if matched_needle < max(1, non_empty_needle - max_needle_skip):
            continue

        length_gap = abs(consumed_hay - max(1, non_empty_needle))
        if length_gap > max(6, non_empty_needle // 3):
            continue

        cand = (s, e, score)
        if best is None:
            best = cand
        else:
            # 先看分数，再看离 cursor 近不近
            if (score > best[2]) or (score == best[2] and s < best[0]):
                best = cand

        if score >= 0.98 and s == start:
            break

    if best is not None and best[2] >= min_score:
        return best
    return None


# ============================================================
# segale / yaml / instances
# ============================================================
def _load_segale(segale_jsonl: str) -> Dict[str, List[Dict[str, Any]]]:
    mp: Dict[str, List[Dict[str, Any]]] = {}
    with open(segale_jsonl, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            r = json.loads(line)
            doc_id = r["doc_id"]
            mp.setdefault(doc_id, []).append(r)

    for k in mp:
        mp[k].sort(
            key=lambda x: int(x["seg_id"]) if str(x["seg_id"]).isdigit() else 10**9
        )
    return mp


def _load_yaml_and_source_sentences(
    yaml_file: str, source_txt: str
) -> Dict[str, List[Tuple[int, float, float, List[str]]]]:
    with open(yaml_file, "r", encoding="utf-8") as f:
        segs = yaml.safe_load(f) or []
    with open(source_txt, "r", encoding="utf-8") as f:
        src_lines = [x.rstrip("\n") for x in f]

    assert len(segs) == len(src_lines), "ref_segments.yaml 行数 必须 == source.txt 行数"

    mp: Dict[str, List[Tuple[int, float, float, List[str]]]] = {}
    for i, (seg, sline) in enumerate(zip(segs, src_lines)):
        doc_id = seg["wav"]
        off_ms = float(seg["offset"]) * 1000.0
        dur_ms = float(seg["duration"]) * 1000.0
        end_ms = off_ms + dur_ms
        toks = _qwen_units(sline, "english")
        mp.setdefault(doc_id, []).append((i, off_ms, end_ms, toks))
    return mp


def _load_instances_log(instances_log: str) -> Dict[str, Dict[str, Any]]:
    """
    关键修复：
    - raw unit 序列长度和 delays 对齐
    - compact unit 序列用于匹配
    - compact_to_raw 用于把匹配区间映射回 raw delay 下标
    """
    mp = {}
    with open(instances_log, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            h = json.loads(line)

            src = h.get("source")
            src_path = (src[0] if isinstance(src, list) else src) or ""
            doc_id = os.path.basename(str(src_path)).replace("\\", "/")

            delays = h.get("delays") or []
            durations = h.get("durations") or []
            elapsed = h.get("elapsed") or []
            intervals = h.get("intervals") or []

            if (not elapsed) or (len(elapsed) != len(delays)):
                elapsed = list(delays)

            m = min(len(delays), len(elapsed))
            delays = list(delays[:m])
            elapsed = list(elapsed[:m])
            if durations:
                durations = list(durations[:m])
            if intervals:
                intervals = list(intervals[:m])

            ts = h.get("prediction_units") or []

            raw_units: List[str] = []
            compact_units: List[str] = []
            compact_to_raw: List[int] = []

            for raw_idx in range(m):
                x = ts[raw_idx] if raw_idx < len(ts) else ""
                u = _norm(x)
                raw_units.append(u)
                if u and u.strip():
                    compact_to_raw.append(raw_idx)
                    compact_units.append(u)

            h["_doc_id"] = doc_id
            h["_source_length_ms"] = _to_ms(h.get("source_length", INF))
            h["_delays"] = delays
            h["_durations"] = durations
            h["_elapsed"] = elapsed
            h["_intervals"] = intervals

            # 两套坐标系
            h["_raw_units"] = raw_units
            h["_asr_units"] = compact_units
            h["_compact_to_raw"] = compact_to_raw

            mp[doc_id] = h
    return mp


# ============================================================
# # Segale src 和 yaml 的匹配
# ============================================================
def _match_src_span_for_seg(
    segale_src_seg: str,
    src_sent_list: List[Tuple[int, float, float, List[str]]],
    list_j: int,
) -> Tuple[int, int, float, float]:
    target = _qwen_units(segale_src_seg, "english")
    if not target:
        _, s_ms, e_ms, _ = src_sent_list[list_j]
        return list_j + 1, 1, s_ms, e_ms

    acc: List[str] = []
    start_ms = None
    end_ms = None
    used = 0
    j = list_j

    while j < len(src_sent_list):
        _, s_ms, e_ms, toks = src_sent_list[j]
        if start_ms is None:
            start_ms = s_ms
        end_ms = e_ms
        acc.extend(toks)
        used += 1

        if acc == target:
            return j + 1, used, float(start_ms), float(end_ms)

        if len(acc) > len(target) and target:
            break
        j += 1

    _, s_ms, e_ms, _ = src_sent_list[list_j]
    return list_j + 1, 1, float(s_ms), float(e_ms)


def _match_src_span_for_seg_by_ids(
    src_ref_ids: List[int],
    src_sent_list: List[Tuple[int, float, float, List[str]]],
) -> Tuple[int, int, float, float]:
    if not src_ref_ids:
        raise ValueError("src_ref_ids is empty")

    global_to_local = {t[0]: i for i, t in enumerate(src_sent_list)}

    indices = []
    for sid in src_ref_ids:
        g0 = int(sid) - 1
        if g0 in global_to_local:
            indices.append(global_to_local[g0])

    if not indices:
        raise ValueError(f"Invalid src_ref_ids: {src_ref_ids} (not in this doc's segments)")

    start_idx = min(indices)
    end_idx = max(indices)

    _, start_ms, _, _ = src_sent_list[start_idx]
    _, _, end_ms, _ = src_sent_list[end_idx]

    new_cursor_sent = end_idx + 1
    num_sent_used = end_idx - start_idx + 1
    return new_cursor_sent, num_sent_used, float(start_ms), float(end_ms)


# ============================================================
# Segale tgt 和 ASR unit 的匹配
# ============================================================

# ------------------------------------------------------------
# # normalize helpers for char-stream matching
# ------------------------------------------------------------

def _is_kept_char(ch: str) -> bool:
    if ch == "'":  # 单引号
        return True
    cat = unicodedata.category(ch)
    return cat.startswith("L") or cat.startswith("N")  # 字母或数字


def _norm_char_stream(text: str) -> str:
    """
    把一段文本转成一个适合做字符流匹配的“规范串”："hello world!" -> "helloworld"
    - NFKC
    - 仅保留字母/数字/单引号
    - 英文转小写
    """
    text = _norm(text)
    return "".join(ch.lower() for ch in text if _is_kept_char(ch))


# ------------------------------------------------------------
# # data structures
# ------------------------------------------------------------

@dataclass
class CompactCharIndex:
    """
    基于 compact units 构建的字符流索引。

    norm_units:
        每个 compact unit 规范化后的字符串
    global_norm:
        全部 norm_units 直接拼接后的全局串
    global_pos_to_unit:
        global_norm 的每个字符对应哪个 compact unit
    global_pos_to_char_in_unit:
        global_norm 的每个字符在对应 compact unit 里的偏移
    unit_start_global:
        每个 compact unit 在 global_norm 中的起始位置
    unit_end_global:
        每个 compact unit 在 global_norm 中的结束位置（开区间）
    """
    norm_units: List[str]
    global_norm: str
    global_pos_to_unit: List[int]
    global_pos_to_char_in_unit: List[int]
    unit_start_global: List[int]
    unit_end_global: List[int]


@dataclass
class UnitMatchResult:
    """
    统一的匹配结果。

    new_cursor_unit:
        下一个 segment 从哪个 compact unit 开始继续找
    u_start, u_end:
        命中的 compact unit span，开区间 [u_start, u_end)
    start_offset:
        在 u_start 这个 unit 的 norm token 内起始偏移
    end_offset:
        在 u_end-1 这个 unit 的 norm token 内结束偏移（开区间）
    method:
        strict / loose / skip_latin / char_exact / merge_split / empty / not_found
    score:
        对 strict/loose/char_exact 可固定为 1.0；fuzzy 用真实分数
    """
    new_cursor_unit: int
    u_start: int
    u_end: int
    start_offset: int = 0
    end_offset: int = 0
    method: str = ""
    score: float = 0.0


# ------------------------------------------------------------
# # build char index over compact units
# ------------------------------------------------------------

def _build_compact_char_index(asr_units: List[str]) -> CompactCharIndex:
    norm_units: List[str] = []
    global_parts: List[str] = []
    global_pos_to_unit: List[int] = []
    global_pos_to_char_in_unit: List[int] = []
    unit_start_global: List[int] = []
    unit_end_global: List[int] = []

    g = 0
    for i, unit in enumerate(asr_units):
        nu = _norm_char_stream(unit)
        norm_units.append(nu)
        unit_start_global.append(g)

        for j, ch in enumerate(nu):
            global_parts.append(ch)
            global_pos_to_unit.append(i)
            global_pos_to_char_in_unit.append(j)
            g += 1

        unit_end_global.append(g)

    return CompactCharIndex(
        norm_units=norm_units,
        global_norm="".join(global_parts),
        global_pos_to_unit=global_pos_to_unit,
        global_pos_to_char_in_unit=global_pos_to_char_in_unit,
        unit_start_global=unit_start_global,
        unit_end_global=unit_end_global,
    )


def _unit_cursor_to_char_cursor(index: CompactCharIndex, unit_i: int) -> int:
    if unit_i <= 0:
        return 0
    if not index.unit_start_global:
        return 0
    if unit_i >= len(index.unit_start_global):
        return len(index.global_norm)
    return index.unit_start_global[unit_i]


# ------------------------------------------------------------
# # optional original char-span helper
# ------------------------------------------------------------

def _build_units_with_offsets_cached(full_doc_tgt_norm: str, asr_units: List[str]):
    """
    这里输入的是 compact asr_units。
    只有当整段 tokenize 后和 compact units 完全一致时，才启用这个“原文字符跨度 -> unit”快速映射。
    注意：这不再是唯一 char 通道。即使这里失败，也可以走 compact-unit char-stream。
    """
    units_with_offsets = qwen_tok.encode_timestamp_with_offsets(full_doc_tgt_norm, "chinese")
    if len(units_with_offsets) != len(asr_units):
        return units_with_offsets, False
    if not all(u[0] == a for u, a in zip(units_with_offsets, asr_units)):
        return units_with_offsets, False
    return units_with_offsets, True


def _match_tgt_units_for_seg_by_char_span(
    units_with_offsets,
    seg_char_start: int,
    seg_char_end: int,
    cursor_unit: int,
) -> Optional[Tuple[int, int]]:
    if seg_char_start < 0 or seg_char_end <= seg_char_start:
        return None
    if not units_with_offsets:
        return None

    i_start_found = next(
        (i for i in range(len(units_with_offsets)) if units_with_offsets[i][2] > seg_char_start),
        None,
    )
    i_end_found = next(
        (i for i in range(len(units_with_offsets) - 1, -1, -1) if units_with_offsets[i][1] < seg_char_end),
        None,
    )
    if i_start_found is None or i_end_found is None:
        return None

    i_start = max(i_start_found, max(0, cursor_unit - 1))
    i_end = max(i_end_found, i_start)
    return i_start, i_end + 1


# ------------------------------------------------------------
# # char-stream exact matcher over compact units
# ------------------------------------------------------------

def _find_by_char_stream_exact(
    seg_text: str,
    char_index: CompactCharIndex,
    unit_i: int,
) -> Optional[Tuple[int, int, int, int]]:
    """
    在 compact units 构建出的 global normalized char stream 里做 exact match。

    返回:
        (u_start, u_end, start_offset, end_offset)

    其中:
    - unit span 是 [u_start, u_end)
    - start_offset 是 u_start 这个 unit 内的起始偏移
    - end_offset 是 u_end-1 这个 unit 内的结束偏移（开区间）
    """
    needle_norm = _norm_char_stream(seg_text)
    if not needle_norm:
        return None

    if not char_index.global_norm:
        return None

    char_cursor = _unit_cursor_to_char_cursor(char_index, unit_i)
    pos = char_index.global_norm.find(needle_norm, char_cursor)
    if pos == -1:
        return None

    start = pos
    end = pos + len(needle_norm)  # 开区间

    start_unit = char_index.global_pos_to_unit[start]
    start_offset = char_index.global_pos_to_char_in_unit[start]

    last = end - 1
    end_unit_inclusive = char_index.global_pos_to_unit[last]
    end_offset = char_index.global_pos_to_char_in_unit[last] + 1  # 开区间

    return start_unit, end_unit_inclusive + 1, start_offset, end_offset


# ------------------------------------------------------------
# # raw/compact span mapping
# ------------------------------------------------------------

def _compact_span_to_raw_span(
    compact_to_raw: List[int],
    c_start: int,
    c_end: int,
) -> Tuple[int, int]:
    """
    compact [c_start, c_end) -> raw [r_start, r_end)
    用于切 delays_all / elapsed_all
    """
    if c_start >= c_end or not compact_to_raw:
        return 0, 0

    if c_start < 0 or c_end > len(compact_to_raw):
        return 0, 0

    r_start = compact_to_raw[c_start]
    r_end = compact_to_raw[c_end - 1] + 1
    return r_start, r_end


# ------------------------------------------------------------
# # main matcher
# 依赖以下外部函数/对象已经在你的工程里存在：
#   _fix_decimal_for_segale_text
#   _find_sublist
#   _find_sublist_loose
#   _find_sublist_merge_split_window
#   _is_latin_token
#   logger
# ------------------------------------------------------------

def _match_tgt_units_for_seg(
    segale_tgt_seg: str,
    tgt_asr_units: List[str],
    unit_i: int,
    doc_id: str,
    seg_id: str,
    char_index: Optional[CompactCharIndex] = None,
) -> UnitMatchResult:
    """
    返回 compact unit 空间下的匹配结果。

    优先级：
    1) strict
    2) loose
    3) skip leading latin tokens
    4) char-stream exact
    5) merge/split local alignment
    """
    segale_tgt_seg = _fix_decimal_for_segale_text(segale_tgt_seg)
    needle = _qwen_units(segale_tgt_seg, "chinese")

    if not needle:
        return UnitMatchResult(
            new_cursor_unit=unit_i,
            u_start=unit_i,
            u_end=unit_i,
            start_offset=0,
            end_offset=0,
            method="empty",
            score=1.0,
        )

    # --------------------------------------------------------
    # 1) strict
    # --------------------------------------------------------
    hit = _find_sublist(tgt_asr_units, needle, unit_i)
    if hit is not None:
        u_start, u_end = hit
        return UnitMatchResult(
            new_cursor_unit=u_end,
            u_start=u_start,
            u_end=u_end,
            start_offset=0,
            end_offset=len(_norm_char_stream(tgt_asr_units[u_end - 1])) if u_end > u_start else 0,
            method="strict",
            score=1.0,
        )

    # --------------------------------------------------------
    # 2) loose
    # --------------------------------------------------------
    hit = _find_sublist_loose(tgt_asr_units, needle, unit_i)
    if hit is not None:
        u_start, u_end = hit
        return UnitMatchResult(
            new_cursor_unit=u_end,
            u_start=u_start,
            u_end=u_end,
            start_offset=0,
            end_offset=len(_norm_char_stream(tgt_asr_units[u_end - 1])) if u_end > u_start else 0,
            method="loose",
            score=1.0,
        )

    # --------------------------------------------------------
    # 3) skip leading latin tokens
    # --------------------------------------------------------
    max_skip = min(3, len(needle) - 1)
    for skip in range(1, max_skip + 1):
        if not _is_latin_token(needle[skip - 1]):
            break

        sub = needle[skip:]
        if not sub:
            break

        h = _find_sublist(tgt_asr_units, sub, unit_i)
        if h is None:
            h = _find_sublist_loose(tgt_asr_units, sub, unit_i)

        if h is not None:
            u_start, u_end = h
            return UnitMatchResult(
                new_cursor_unit=u_end,
                u_start=u_start,
                u_end=u_end,
                start_offset=0,
                end_offset=len(_norm_char_stream(tgt_asr_units[u_end - 1])) if u_end > u_start else 0,
                method=f"skip_latin_{skip}",
                score=1.0,
            )

    # --------------------------------------------------------
    # 4) char-stream exact over compact units
    # --------------------------------------------------------
    if char_index is not None:
        char_hit = _find_by_char_stream_exact(segale_tgt_seg, char_index, unit_i)
        if char_hit is not None:
            u_start, u_end, start_offset, end_offset = char_hit
            try:
                logger.info(
                    "[match][char-exact] doc=%s seg_id=%s cursor=%d start=%d end=%d so=%d eo=%d needle_len=%d",
                    doc_id, seg_id, unit_i, u_start, u_end, start_offset, end_offset, len(needle)
                )
            except Exception:
                pass

            return UnitMatchResult(
                new_cursor_unit=u_end,
                u_start=u_start,
                u_end=u_end,
                start_offset=start_offset,
                end_offset=end_offset,
                method="char_exact",
                score=1.0,
            )

    # --------------------------------------------------------
    # 5) merge/split local alignment
    # --------------------------------------------------------
    fuzzy = _find_sublist_merge_split_window(
        tgt_asr_units,
        needle,
        unit_i,
        # window_size=240,
        # min_score=0.90,
        # max_hay_skip=2,
        # max_needle_skip=1,
        # max_start_drift=160,
        window_size=280,
        min_score=0.86,
        max_hay_skip=3,
        max_needle_skip=2,
        max_start_drift=180,
    )
    if fuzzy is not None:
        f_start, f_end, f_score = fuzzy
        try:
            logger.info(
                "[match][merge-split] doc=%s seg_id=%s cursor=%d start=%d end=%d score=%.3f needle_len=%d",
                doc_id, seg_id, unit_i, f_start, f_end, f_score, len(needle)
            )
        except Exception:
            pass

        return UnitMatchResult(
            new_cursor_unit=f_end,
            u_start=f_start,
            u_end=f_end,
            start_offset=0,
            end_offset=len(_norm_char_stream(tgt_asr_units[f_end - 1])) if f_end > f_start else 0,
            method="merge_split",
            score=float(f_score),
        )

    # --------------------------------------------------------
    # not found
    # --------------------------------------------------------
    try:
        logger.warning(
            "[skip][tgt-not-found] doc=%s seg_id=%s cursor=%d needle_len=%d needle=%s asr_ctx=%s",
            doc_id,
            seg_id,
            unit_i,
            len(needle),
            needle[:20],
            tgt_asr_units[unit_i:min(len(tgt_asr_units), unit_i + 60)],
        )
    except Exception:
        pass

    return UnitMatchResult(
        new_cursor_unit=unit_i,
        u_start=unit_i,
        u_end=unit_i,
        start_offset=0,
        end_offset=0,
        method="not_found",
        score=0.0,
    )


# ------------------------------------------------------------
# optional helper: full pipeline usage
# ------------------------------------------------------------

def build_target_matcher_context(tgt_asr_units: List[str]) -> CompactCharIndex:
    """
    在处理整篇文档前调用一次即可。
    """
    return _build_compact_char_index(tgt_asr_units)


def match_segment_and_map_raw(
    segale_tgt_seg: str,
    tgt_asr_units: List[str],
    compact_to_raw: List[int],
    unit_i: int,
    doc_id: str,
    seg_id: str,
    char_index: Optional[CompactCharIndex] = None,
):
    """
    一个方便上层直接调用的包装函数。
    返回:
        match_result, raw_span
    """
    mr = _match_tgt_units_for_seg(
        segale_tgt_seg=segale_tgt_seg,
        tgt_asr_units=tgt_asr_units,
        unit_i=unit_i,
        doc_id=doc_id,
        seg_id=seg_id,
        char_index=char_index,
    )
    raw_span = _compact_span_to_raw_span(compact_to_raw, mr.u_start, mr.u_end)
    return mr, raw_span

# ============================================================
# 主流程
# ============================================================
def step3_longyaal(
    yaml_file: str,
    source_sentences_file: str,
    instances_log: str,
    segale_file: str,
    output_folder: str,
    bleu_tokenizer: str,
):
    os.makedirs(output_folder, exist_ok=True)

    segale_by_doc = _load_segale(segale_file)
    sent_by_doc = _load_yaml_and_source_sentences(yaml_file, source_sentences_file)
    inst_by_doc = _load_instances_log(instances_log)

    instances: List[Instance] = []
    instances_dict: List[Dict[str, Any]] = []

    global_idx = 0

    for doc_id, segs in segale_by_doc.items():
        if doc_id not in sent_by_doc:
            logger.warning(f"[skip] doc missing in yaml/source.txt: {doc_id}")
            continue
        if doc_id not in inst_by_doc:
            logger.warning(f"[skip] doc missing in instances.log: {doc_id}")
            continue

        inst = inst_by_doc[doc_id]

        asr_units = inst.get("_asr_units", [])
        compact_to_raw = inst.get("_compact_to_raw", [])
        if not asr_units:
            logger.warning(f"[skip] doc missing asr units in instances.log: {doc_id}")
            continue

        delays_all = inst["_delays"]
        durations_all = inst["_durations"]
        elapsed_all = inst["_elapsed"]

        # compact 空间和 raw 时间空间长度本来就不必相等；
        # 这里只检查 raw delays / elapsed
        m_raw = min(len(delays_all), len(elapsed_all))
        delays_all = delays_all[:m_raw]
        elapsed_all = elapsed_all[:m_raw]
        if durations_all:
            durations_all = durations_all[:m_raw]

        # compact_to_raw 的最后一个 raw 索引不能超出 raw 时间长度
        valid_compact_len = 0
        for ridx in compact_to_raw:
            if 0 <= ridx < m_raw:
                valid_compact_len += 1
            else:
                break

        if valid_compact_len != len(compact_to_raw):
            logger.warning(
                "[warn] compact_to_raw out of raw range for %s: compact=%d valid=%d raw=%d",
                doc_id, len(compact_to_raw), valid_compact_len, m_raw
            )
            compact_to_raw = compact_to_raw[:valid_compact_len]
            asr_units = asr_units[:valid_compact_len]

        char_index = build_target_matcher_context(asr_units)

        cursor_unit = 0
        cursor_sent = 0
        doc_sent_list = sent_by_doc[doc_id]

        full_doc_tgt = _fix_decimal_for_segale_text(_norm(inst.get("prediction_text") or ""))
        units_with_offsets, char_span_ok = _build_units_with_offsets_cached(full_doc_tgt, asr_units)
        if not char_span_ok:
            logger.warning(
                "[warn][char-span-fallback] doc=%s 整段 tokenize 与 compact asr_units 不一致，退化为 token 匹配。 full_tok_len=%d asr_units_len=%d",
                doc_id, len(units_with_offsets), len(asr_units),
            )

        search_start = 0
        seg_char_spans: List[Tuple[int, int]] = []
        for seg in segs:
            seg_tgt = seg.get("tgt", "")
            seg_norm = _fix_decimal_for_segale_text(_norm(seg_tgt).strip())
            if not seg_norm:
                seg_char_spans.append((-1, -1))
                continue

            idx = full_doc_tgt.find(seg_norm, search_start)
            if idx >= 0:
                seg_char_spans.append((idx, idx + len(seg_norm)))
                search_start = idx + len(seg_norm)
            else:
                seg_char_spans.append((-1, -1))

        for seg_idx, seg in enumerate(segs):
            seg_src = seg.get("src", "")
            seg_tgt = seg.get("tgt", "")
            seg_ref = seg.get("ref", "")

            # 3.1 源跨度
            src_ref_ids = seg.get("src_ref_ids") or []
            if src_ref_ids:
                try:
                    cursor_sent, _, seg_start_ms, seg_end_ms = _match_src_span_for_seg_by_ids(
                        src_ref_ids, doc_sent_list
                    )
                except Exception as e:
                    logger.warning(
                        "[fallback][src-ref-ids-invalid] doc=%s seg_id=%s src_ref_ids=%s err=%s",
                        doc_id, seg.get("seg_id"), src_ref_ids, e
                    )
                    list_j = max(0, min(cursor_sent - 1, len(doc_sent_list) - 1))
                    cursor_sent, _, seg_start_ms, seg_end_ms = _match_src_span_for_seg(
                        seg_src, doc_sent_list, list_j
                    )
            else:
                list_j = max(0, min(cursor_sent - 1, len(doc_sent_list) - 1))
                cursor_sent, _, seg_start_ms, seg_end_ms = _match_src_span_for_seg(
                    seg_src, doc_sent_list, list_j
                )

            seg_source_len_ms = max(1.0, seg_end_ms - seg_start_ms)

            # 3.2 tgt -> compact unit span
            char_start, char_end = seg_char_spans[seg_idx] if seg_idx < len(seg_char_spans) else (-1, -1)
            if char_span_ok:
                hit = _match_tgt_units_for_seg_by_char_span(
                    units_with_offsets, char_start, char_end, cursor_unit
                )
            else:
                hit = None

            if hit is not None:
                c_start, c_end = hit
                cursor_unit = c_end
                match_method = "char_span_full_doc"
                start_offset = 0
                end_offset = len(_norm_char_stream(asr_units[c_end - 1])) if c_end > c_start else 0
            else:
                mr = _match_tgt_units_for_seg(
                    segale_tgt_seg=seg_tgt,
                    tgt_asr_units=asr_units,
                    unit_i=cursor_unit,
                    doc_id=doc_id,
                    seg_id=str(seg.get("seg_id")),
                    char_index=char_index,
                )
                cursor_unit = mr.new_cursor_unit
                c_start = mr.u_start
                c_end = mr.u_end
                match_method = mr.method
                start_offset = mr.start_offset
                end_offset = mr.end_offset

            # compact -> raw
            r_start, r_end = _compact_span_to_raw_span(compact_to_raw, c_start, c_end)

            seg_delays = delays_all[r_start:r_end]
            seg_elapsed = elapsed_all[r_start:r_end]

            if not seg_delays:
                logger.warning(
                    "[skip][empty-matched-units] doc=%s seg_id=%s cursor_unit=%d c_start=%d c_end=%d r_start=%d r_end=%d "
                    "len(asr_units)=%d len(delays_all)=%d len(elapsed_all)=%d seg_tgt_len=%d",
                    doc_id,
                    seg.get("seg_id"),
                    cursor_unit,
                    c_start,
                    c_end,
                    r_start,
                    r_end,
                    len(asr_units),
                    len(delays_all),
                    len(elapsed_all),
                    len((seg_tgt or "").strip()),
                )
                continue

            # 3.3 转成 segment 相对时间
            seg_delays_rel = [max(0.0, float(d) - seg_start_ms) for d in seg_delays]
            seg_elapsed_rel = [max(0.0, float(e) - seg_start_ms) for e in seg_elapsed]

            new_seg_dict = {
                "index": global_idx,
                "doc_id": doc_id,
                "seg_id": seg.get("seg_id"),

                "source": seg_src,
                "reference": seg_ref,

                "source_length": seg_source_len_ms,
                "delays": seg_delays_rel,
                "elapsed": seg_elapsed_rel,
                "recording_end": seg_source_len_ms,

                "_compact_u_start": c_start,
                "_compact_u_end": c_end,
                "_raw_u_start": r_start,
                "_raw_u_end": r_end,
                "_seg_start_ms": seg_start_ms,
                "_seg_end_ms": seg_end_ms,

                "_match_method": match_method,
                "_start_offset": start_offset,
                "_end_offset": end_offset,

                "prediction": seg.get("tgt", ""),
                "raw_units": inst["_raw_units"][r_start:r_end]
            }

            instances_dict.append(new_seg_dict)
            instances.append(Instance(new_seg_dict, latency_unit="word"))
            global_idx += 1

    with open(
        os.path.join(output_folder, "instances.resegmented.json"),
        "w",
        encoding="utf-8",
    ) as f:
        f.write(json.dumps(instances_dict, ensure_ascii=False, indent=2) + "\n")

    scores = evaluate_instances(instances, bleu_tokenizer)
    with open(
        os.path.join(output_folder, "scores.resegmented.csv"),
        "w",
        encoding="utf-8",
    ) as f:
        f.write("\t".join(scores.keys()) + "\n")
        f.write("\t".join([f"{v:.4f}" for v in scores.values()]) + "\n")

    logger.info(f"Done. segments={len(instances)}. Output -> {output_folder}")


# ============================================================
# CLI
# ============================================================
def build_parser():
    parser = ArgumentParser()
    parser.add_argument(
        "--yaml_file",
        type=str,
        default="data/input/ACL.ACLdev2023.en-xx.gold_segments.yaml",
    )
    parser.add_argument(
        "--source_sentences_file",
        type=str,
        default="data/input/ACL.6060.dev.en-xx.en.txt",
    )
    parser.add_argument(
        "--instances_log",
        type=str,
        default="data/output_qwen_asr3/instances.log",
    )
    parser.add_argument(
        "--segale_file",
        type=str,
        default="data/output_segale3/hyp/aligned_spacy_hyp.jsonl",
    )
    parser.add_argument(
        "--output_folder",
        type=str,
        default="data/output_longyaal3_fixed",
    )
    parser.add_argument(
        "--bleu_tokenizer",
        type=str,
        default="zh",
    )
    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    step3_longyaal(
        yaml_file=args.yaml_file,
        source_sentences_file=args.source_sentences_file,
        instances_log=args.instances_log,
        segale_file=args.segale_file,
        output_folder=args.output_folder,
        bleu_tokenizer=args.bleu_tokenizer,
    )


if __name__ == "__main__":
    main()
